bored_games_app/urls.py
from django.urls import path
from . import views

app_name = "bored_games"

urlpatterns = [
    # Home page / Landing page / Welcome page
    path("", views.landing_page, name = "landing"),

    # Page to display all available games
    path("games/", views.games_page, name = "games"),

    # Page for details of a single game
    path("games/<int:id>/", views.game_details, name = "game_detail"),

    # Form to add new game into database
    path("add_game/", views.new_games, name = "add_game"),

    # Form to add new review for a game
    path("add_review/<int:id>/", views.new_reviews, name = "add_review"),

    # Form to add new copy/instance of an existing game in the database (no template rendered)
    path("add_copy/<int:id>/", views.new_copy, name = "add_copy"),

    # Form to add copies of any existing game in the database (not only a particular game)
    path("add_copy/", views.new_copies, name = "add_copies"),

    # Form to rent an available copy/instance of a game (no template rendered)
    path("rent_game/<int:id>/", views.game_rentals, name = "rent_game"),

    # Page to view user's rented games and user's reviews
    path("profile/", views.user_rentals, name = "profile"),

    # Form to remove rental (no template rendered)
    path("remove_rental/<int:pk>/", views.rental_return, name = "remove_rental"),

    # Form to remove game instance added by user (no template rendered)
    path("remove_game_instance/<int:pk>/", views.game_instance_delete, name = "remove_game_instance"),

    # Form to edit user's existing review
    path("edit_review/<int:pk>/", views.review_edit, name = "edit_review"),

    # Form to delete review added by user (no template rendered)
    path("delete_review/<int:pk>/", views.delete_review, name = "delete_review"),

    # Form to register new user
    path("registration/", views.RegistrationView.as_view(), name = "registration")
]

bored_games_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bored_games/', include('bored_games_app.urls')),
    path('', RedirectView.as_view(url = 'bored_games/')),
    path('accounts/', include('django.contrib.auth.urls'))
]

bored_games_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.

class BoardGame(models.Model):
    """Model for each board game added into the database by users."""

    title = models.CharField(max_length = 100)
    min_no_of_players = models.IntegerField(validators = [MinValueValidator(1)])
    max_no_of_players = models.IntegerField(validators = [MinValueValidator(1)])
    summary = models.TextField(max_length = 200, null = True, blank = True)

    # Field is automatically set to date when object is first created
    date_added = models.DateField(auto_now_add = True)
    # Field is automatically set to now when object is saved
    date_modified = models.DateTimeField(auto_now = True)

    def get_absolute_url(self):
        return reverse("bored_games:game_detail", kwargs = {"pk": self.pk})

    def __str__(self):
        return self.title

    
class BoardGameInstance(models.Model):
    """Model for each instance of a board game added into the database by users."""

    game = models.ForeignKey("BoardGame", on_delete = models.CASCADE)
    
    latest_borrower = models.ForeignKey(User, related_name = "latest_borrower", 
                                        on_delete = models.SET_NULL,
                                        null = True, blank = True)
                                        
    added_by = models.ForeignKey(User, related_name = "added_by",
                                on_delete = models.SET_NULL,
                                null = True, blank = True)

    LOAN_STATUS = (
        ("a", "Available"),
        ("r", "Rented")
    )

    status = models.CharField(max_length = 1, choices = LOAN_STATUS, default = "a")

    # Field is automatically set to date when object is first created
    date_added = models.DateField(auto_now_add = True)
    # Field is automatically set to now when object is saved
    date_modified = models.DateTimeField(auto_now = True)

    def __str__(self):
        return f"{self.id} {self.game.title}"


class BoardGameRental(models.Model):
    """Model for rentals of board game instances by users."""

    borrower = models.ForeignKey(User, on_delete = models.CASCADE)
    game_instance = models.ForeignKey("BoardGameInstance", on_delete = models.CASCADE)

    # Field is automatically set to date when object is first created
    date_rented = models.DateField(auto_now_add = True)

    def __str__(self):
        return f"{self.borrower} rented {self.game_instance.game.title} on {self.date_rented}"


class BoardGameReview(models.Model):
    """Model for reviews of board games written by users."""

    review = models.TextField()
    stars = models.IntegerField(validators = [MinValueValidator(0), MaxValueValidator(5)], null = True, blank = True)
    
    game = models.ForeignKey("BoardGame", on_delete = models.RESTRICT, null = True)
    review_author = models.ForeignKey(User, on_delete = models.CASCADE)

    # Field is automatically set to date when object is first created
    date_written = models.DateField(auto_now_add = True)
    # Field is automatically set to now when object is saved
    date_edited = models.DateTimeField(auto_now = True)

    def __str__(self):
        """Return a string representation of the first 300 characters of a Review object's text."""
        return f"{self.review[:300]}"

bored_games_app/forms.py
from django.forms import ModelForm
from .models import *

class BoardGameForm(ModelForm):

    class Meta:
        model = BoardGame
        fields = "__all__"

        labels = {
            "title": "Title",
            "min_no_of_players": "Minimum number of players",
            "max_no_of_players": "Maximum number of players",
            "summary": "Summary"
        }

        error_messages = {
            "min_no_of_players": {
                "min_value": "Yo! Min value is 1!"
            },
            "max_no_of_players": {
                "min_value": "Yo! Min value is 1!"
            }
        }


class BoardGameInstanceForm(ModelForm):

    class Meta:
        model = BoardGameInstance
        fields = ["game"]


class BoardGameRentalForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(BoardGameRentalForm, self).__init__(*args, **kwargs)
        self.fields["game_instance"].queryset = BoardGameInstance.objects.filter(status="a")

    class Meta:
        model = BoardGameRental
        fields = ["game_instance"]

        labels = {
            "game_instance": "Choose a game"
        }


class ReviewForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(ReviewForm, self).__init__(*args, **kwargs)
        self.fields["game"].widget.attrs["readonly"] = True

    class Meta:
        model = BoardGameReview
        fields = ["game", "review"]

        labels = {
            "game": "Game",
            "review": "Review"
        }

bored_games_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.http import Http404
from django.views.generic import CreateView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from .models import *
from .forms import *

# Create your views here.

# VIEW FUNCTIONS

def landing_page(request):
    games = BoardGame.objects.count()
    game_instances = BoardGameInstance.objects.count()
    context = {
        "games": games,
        "game_instances": game_instances
    }
    return render(request, "bored_games_app/index.html", context = context)


def games_page(request):
    games = BoardGameInstance.objects.filter(status = "a").distinct().order_by("game")
    rented_games = BoardGameInstance.objects.filter(status = "r").distinct().order_by("game")

    if BoardGameRental.objects.filter(borrower = request.user.id).count() >= 3:
        limit_reached = True
    else:
        limit_reached = False
    
    if BoardGameInstance.objects.filter(status = "r").count() == 0:
        no_rentals = True
    else:
        no_rentals = False

    context = {
        "games": games,
        "rented_games": rented_games,
        "limit_reached": limit_reached,
        "no_rentals": no_rentals,
        }
    return render(request, "bored_games_app/games.html", context = context)


def game_details(request, id):
    game = get_object_or_404(BoardGame, pk = id)
    reviews = BoardGameReview.objects.filter(game = id)

    if BoardGameReview.objects.filter(game = id).filter(review_author = request.user).count() > 0:
        already_reviewed = True
    else:
        already_reviewed = False

    if reviews.count() == 0:
        no_reviews = True
    else:
        no_reviews = False

    context = {
        "game": game,
        "reviews": reviews,
        "no_reviews": no_reviews,
        "already_reviewed": already_reviewed
        }
    return render(request, "bored_games_app/game_detail.html", context = context)


@login_required
def new_games(request):

    if request.method == "POST":
        form = BoardGameForm(request.POST)

        if form.is_valid():
            game = form.save()
            BoardGameInstance.objects.get_or_create(game = game, added_by = request.user)
            return redirect(reverse("bored_games:game_detail", kwargs = {"id": game.id}))
        
    else:
        form = BoardGameForm()

    return render(request, "bored_games_app/add_game.html", context = {"form": form})


@login_required
def new_reviews(request, id):

    game = BoardGame.objects.get(pk = id)

    if request.method == "POST":
        form = ReviewForm(request.POST, initial={"game": game})

        if form.is_valid():
            review = form.save(commit = False)
            review.review_author = request.user
            review.save()
            return redirect(reverse("bored_games:game_detail", kwargs = {"id": review.game.id}))
    
    else:
        form = ReviewForm(initial={"game": game})

    return render(request, "bored_games_app/add_review.html", context = {"form": form})


@login_required
def new_copy(request, id):

    game = BoardGame.objects.get(pk = id)
    obj = BoardGameInstance.objects.create(game = game, added_by = request.user)
    obj.save()

    return redirect(reverse("bored_games:games"))

@login_required
def new_copies(request):

    if request.method == "POST":
        form = BoardGameInstanceForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect(reverse("bored_games:games"))
    
    else:
        form = BoardGameInstanceForm()
    
    return render(request, "bored_games_app/add_copy.html", context = {"form": form})


@login_required
def game_rentals(request, id):

    game = BoardGameInstance.objects.get(pk = id)
    game.status = "r"
    game.latest_borrower = request.user
    game.save()

    rental, created = BoardGameRental.objects.get_or_create(game_instance = game, borrower = request.user)
    rental.save()

    return redirect(reverse("bored_games:profile"))


@login_required
def user_rentals(request):
    rentals = BoardGameRental.objects.filter(borrower = request.user)
    games = BoardGameInstance.objects.filter(added_by = request.user).order_by("game")
    reviews = BoardGameReview.objects.filter(review_author = request.user)

    context = {
        "rentals": rentals,
        "games": games,
        "reviews": reviews
    }
    return render(request, "bored_games_app/my_rentals.html", context = context)


def rental_return(request, pk):
    rental = BoardGameRental.objects.get(pk = pk)
    obj, created = BoardGameInstance.objects.get_or_create(id = rental.game_instance.id)
    obj.status = "a"
    rental.delete()
    obj.save()
    return redirect(reverse("bored_games:profile"))


def game_instance_delete(request, pk):
    game = BoardGameInstance.objects.get(pk = pk)
    game.delete()
    return redirect(reverse("bored_games:profile"))


@login_required
def review_edit(request, pk):
    
    review = BoardGameReview.objects.get(pk = pk)

    if review.review_author != request.user:
        raise Http404
 
    if request.method != "POST":
        form = ReviewForm(instance = review)
    else:
        form = ReviewForm(instance = review, data = request.POST)
 
        if form.is_valid():
            form.save()
            return redirect("bored_games:profile")

    context = {
        "review": review,
        "form": form
        }
    return render(request, "bored_games_app/edit_review.html", context = context)


def delete_review(request, pk):
    review = BoardGameReview.objects.get(pk = pk)
    review.delete()
    return redirect(reverse("bored_games:profile"))


# CLASS-BASED VIEWS

class RegistrationView(CreateView):

    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "bored_games_app/registration.html"

bored_games_app/templates/bored_games_app/add_copy.html
{% extends "base.html" %}
{% load static %}

{% block stylesheet %}
<link rel="stylesheet" href="/static/bored_games_app/forms.css">
{% endblock stylesheet %}

{% block title %}
 <title>Bored Games – Add Copy of Game</title>
{% endblock title %}

{% block page %}
<div class="page">

    <div class="content">
        <h1>Add a copy of a game</h1>
        <form action="" method="POST">
            {% csrf_token %}
            <table>
                {{ form }}
            </table>
    
            <button type="submit">Add copy</button>
        </form>
    </div>
{% endblock page %}

bored_games_app/templates/bored_games_app/add_game.html
{% extends "base.html" %}
{% load static %}

{% block stylesheet %}
<link rel="stylesheet" href="/static/bored_games_app/forms.css">
{% endblock stylesheet %}

{% block title %}
 <title>Bored Games – Add New Game</title>
{% endblock title %}

{% block page %}
<div class="page">

    <div class="content">
        <h1>Add New Game</h1>
        <form action="" method="POST">
            {% csrf_token %}
            <table>
                {{ form }}
            </table>
    
            <button type="submit">Add game</button>
        </form>
    </div>
{% endblock page %}

bored_games_app/templates/bored_games_app/add_review.html
{% extends "base.html" %}
{% load static %}

{% block stylesheet %}
<link rel="stylesheet" href="/static/bored_games_app/forms.css">
{% endblock stylesheet %}

{% block title %}
 <title>Bored Games – Add New Review</title>
{% endblock title %}

{% block page %}
<div class="page">

    <div class="content">
        <h1>Add New Review</h1>
        <form action="" method="POST">
            {% csrf_token %}
            <table>
                {{ form }}
            </table>
    
            <button type="submit">Add review</button>
        </form>
    </div>
{% endblock page %}

bored_games_app/templates/bored_games_app/edit_review.html
{% extends "base.html" %}
{% load static %}

{% block stylesheet %}
<link rel="stylesheet" href="/static/bored_games_app/forms.css">
{% endblock stylesheet %}

{% block title %}
 <title>Bored Games – Edit Review</title>
{% endblock title %}

{% block page %}
<div class="page">

    <div class="content">
        <h1>Edit Review</h1>
        <form action="" method="POST">
            {% csrf_token %}
            <table>
                {{ form.as_p }}
            </table>
    
            <button type="submit">Save changes</button>
        </form>
    </div>
{% endblock page %}

bored_games_app/templates/bored_games_app/game_detail.html
{% extends "base.html" %}
{% load static %}

{% block stylesheet %}
<link rel="stylesheet" href="/static/bored_games_app/game_detail.css">
{% endblock stylesheet %}

{% block title %}
 <title>Bored Games – {{ game.title }}</title>
{% endblock title %}

{% block page %}
{% if no_reviews != True %}
<div class="page">
{% else %}
<div class="no-reviews">
{% endif %}
    <h1>Bored Games</h1>

    <div class="buttons">
        <a href="{% url "bored_games:add_copy" game.id %}" id="add-copy">Add a new copy of this game</a>
        {% if already_reviewed != True %}
            <a href="{% url "bored_games:add_review" game.id %}" id="add-review">Add review</a>
        {% endif %}
    </div>

    <div class="game-field">
        <h2>{{ game.title }}</h2>
        <div class="players">
            <ul>
                <li>Number of players:</li>
                {% if game.min_no_of_players == game.max_no_of_players %}
                    <li>{{ game.min_no_of_players }}</li>
                {% else %}
                    <li>{{ game.min_no_of_players }} – {{ game.max_no_of_players }}</li>
                {% endif %}
            </ul>
        </div>
    </div>

    <div class="summary-field">
        <h2>Summary</h2>
        <div class="summary">
            <li><span id="summary">{{ game.summary }}</span></li>
        </div>
    </div>

    <div class="review-field">
        <h2>Reviews</h2>
        <div class="reviews">
            {% for review in reviews %}
                <ul>
                    <li><span id="reviewer">{{ review.review_author }}:</span></li>
                    <li><span id="review">{{ review|wordwrap:100|linebreaks }}</span></li>
                </ul>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock page %}

bored_games_app/templates/bored_games_app/games.html
{% extends "base.html" %}
{% load static %}

{% block stylesheet %}
<link rel="stylesheet" href="/static/bored_games_app/games.css">
{% endblock stylesheet %}

{% block title %}
 <title>Bored Games – Games</title>
{% endblock title %}

{% block page %}
<div class="page">
    <h1>Bored Games</h1>

    <div class="buttons">
        <a href="{% url "bored_games:add_game" %}" id="add-game">Add new game</a>
        <a href="{% url "bored_games:add_copies" %}" id="add-game">Add new copies of games</a>
    </div>

    <div class="content">
        <ul>
            <div class="game">
                <li>Title</li>
                <li>Number of Players</li>
                <li>Games Available</li>
            </div>

            {% for game in games %}
                <div class="game-data">
                    <a href="{% url "bored_games:game_detail" game.game.id %}">
                        <li>{{ game.game.title }}</li>
                    </a>
                    {% if game.game.min_no_of_players == game.game.max_no_of_players %}
                        <li>{{ game.game.min_no_of_players }}</li>
                    {% else %}
                        <li>{{ game.game.min_no_of_players }} – {{ game.game.max_no_of_players }}</li>
                    {% endif %}
                    {% if user.is_authenticated %}
                        {% if limit_reached == True %}
                            <div class="message">
                                <li>Return at least 1 game to rent this game</li>
                            </div>
                        {% else %}
                            <li>
                                <a href="{% url "bored_games:rent_game" game.id %}" class="button">Rent the Game!</a>
                            </li>
                        {% endif %}
                    {% else %}
                        <li>Log in to rent games</li>
                    {% endif %}
                </div>
            {% endfor %}
        </ul>
    </div>

    {% if no_rentals != True %}
        <div class="rented-content">
            <ul>
                <div class="rented-game">
                    <li>Title</li>
                    <li>Number of Players</li>
                    <li class="checkmark">On loan to</li>
                </div>

                {% for game in rented_games %}
                    <div class="rented-game-data">
                        <a href="{% url "bored_games:game_detail" game.game.id %}">
                            <li>{{ game.game.title }}</li>
                        </a>
                        {% if game.game.min_no_of_players == game.game.max_no_of_players %}
                            <li>{{ game.game.min_no_of_players }}</li>
                        {% else %}
                            <li>{{ game.game.min_no_of_players }} – {{ game.game.max_no_of_players }}</li>
                        {% endif %}
                        <li class="checkmark">{{ game.latest_borrower }}</li>
                    </div>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
</div>
{% endblock page %}

bored_games_app/templates/bored_games_app/index.html
{% extends "base.html" %}
{% load static %}

{% block stylesheet %}
<link rel="stylesheet" href="/static/bored_games_app/landing.css">
{% endblock stylesheet %}

{% block title %}
 <title>Bored Games – Welcome</title>
{% endblock title %}

{% block page %}
<div class="page">
    <h1>Bored Games</h1>

    <div class="content">
        <h2>Welcome to our board gaming club!</h2>
        <ul>
            <li>We currently have a total of
                <span id="copies">{{ game_instances }} copies</span> of
                <span id="games">{{ games }} games</span>
            </li>
            <li>You can rent up to three games at a time from our collection</li>
            <li>You can add new games to our collection</li>
            <li>You can also add new copies of the games in our collection</li>
        </ul>
        <div class="button">
            <a href="{% url "bored_games:games" %}">
                Browse our games!
             </a>

        </div>
    </div>
{% endblock page %}

bored_games_app/templates/bored_games_app/my_rentals.html
{% extends "base.html" %}
{% load static %}

{% block stylesheet %}
<link rel="stylesheet" href="/static/bored_games_app/my_rentals.css">
{% endblock stylesheet %}

{% block title %}
 <title>Bored Games – Profile</title>
{% endblock title %}

{% block page %}
<div class="page">
    <h1>Hi, <span class="username">{{ user.get_username }}</span>!</h1>

    <div class="content">
        <h2>Your current rentals</h2>
        <ul>
            <div class="game">
                <li>Title</li>
                <li>Number of Players</li>
                <li>Return game</li>
            </div>

            {% for rental in rentals %}
                <div class="game-data">
                    <a href="{% url "bored_games:game_detail" rental.game_instance.game.id %}">
                        <li>{{ rental.game_instance.game }}</li>
                    </a>
                    {% if rental.game_instance.game.min_no_of_players == rental.game_instance.game.max_no_of_players %}
                        <li>{{ rental.game_instance.game.min_no_of_players }}</li>
                    {% else %}
                        <li>{{ rental.game_instance.game.min_no_of_players }} – {{ rental.game_instance.game.max_no_of_players }}</li>
                    {% endif %}
                    <li>
                        <a href="{% url "bored_games:remove_rental" rental.pk %}" class="button">Return</a>
                    </li>
                </div>
            {% endfor %}
        </ul>

        <h2 id="user-games">Your games</h2>
        <ul>
            <div class="game">
                <li>Title</li>
                <li>Number of Players</li>
                <li>On loan to / Available</li>
            </div>

            {% for game in games %}
                <div class="game-data">
                    <a href="{% url "bored_games:game_detail" game.game.id %}">
                        <li>{{ game.game }}</li>
                    </a>
                    {% if game.game.min_no_of_players == game.game.max_no_of_players %}
                        <li>{{ game.game.min_no_of_players }}</li>
                    {% else %}
                        <li>{{ game.game.min_no_of_players }} – {{ game.game.max_no_of_players }}</li>
                    {% endif %}
                    {% if game.status == "a" %}
                        <li>
                            <a href="{% url "bored_games:remove_game_instance" game.pk %}" class="button">Delete</a>
                        </li>
                    {% else %}
                        <li>{{ game.latest_borrower }}</li>
                    {% endif %}
                </div>
            {% endfor %}
        </ul>

        <h2 id="review">Your game reviews</h2>
        <ul>
            <div class="review">
                <li>Game</li>
                <li>Review</li>
                <li>Edit review</li>
                <li>Delete review</li>
            </div>

            {% for review in reviews %}
                <div class="review-data">
                    <a href="{% url "bored_games:game_detail" review.game.id %}">
                        <li>{{ review.game }}</li>
                    </a>
                    <li>{{ review|wordwrap:300|linebreaks }}</li>
                    <li>
                        <a href="{% url "bored_games:edit_review" review.pk %}" class="button">Edit</a>
                    </li>
                    <li>
                        <a href="{% url "bored_games:delete_review" review.pk %}" class="button">Delete</a>
                    </li>
                </div>
            {% endfor %}
        </ul>
    </div>
{% endblock page %}

bored_games_app/templates/bored_games_app/registration.html
{% extends "base.html" %}
{% load static %}

{% block stylesheet %}
<link rel="stylesheet" href="/static/bored_games_app/registration.css">
{% endblock stylesheet %}

{% block title %}
 <title>Bored Games – Register</title>
{% endblock title %}

{% block page %}
<div class="page">

    <div class="content">
        <h1>Register new user</h1>
        <form action="" method="POST">
            {% csrf_token %}
            <table>
                {{ form.as_p }}
            </table>
    
            <button type="submit">Register</button>
        </form>
    </div>
{% endblock page %}

bored_games_app/templates/bored_games_app/rent_game.html
{% extends "base.html" %}
{% load static %}

{% block stylesheet %}
<link rel="stylesheet" href="/static/bored_games_app/forms.css">
{% endblock stylesheet %}

{% block title %}
 <title>Bored Games – Rent Game</title>
{% endblock title %}

{% block page %}
<div class="page">

    <div class="content">
        <h1>Rent a game</h1>
        <form action="" method="POST">
            {% csrf_token %}
            <table>
                {{ form }}
            </table>
    
            <button type="submit">Rent game</button>
        </form>
    </div>
{% endblock page %}